-- ============================================================================
-- Seed concierge tasks for Stages 1–3
-- Migration 003: Compliance journey task definitions
-- ============================================================================

-- Stage 1: Register & Exist (6 tasks)
INSERT INTO concierge_tasks (stage_id, title, description, action_type, action_url, domain_id, display_order, applies_to) VALUES
((SELECT id FROM concierge_stages WHERE stage_number = 1), 'Register with HMRC', 'Register as self-employed or for Corporation Tax with HMRC. This is a legal requirement for all UK businesses.', 'external_link', 'https://www.gov.uk/register-for-self-assessment', (SELECT id FROM compliance_domains WHERE name = 'Formation & Registration'), 1, '{"business_type": ["sole_trader"]}'),
((SELECT id FROM concierge_stages WHERE stage_number = 1), 'Register with HMRC for Corporation Tax', 'Register your limited company for Corporation Tax within 3 months of starting to trade.', 'external_link', 'https://www.gov.uk/limited-company-formation/set-up-your-company-for-corporation-tax', (SELECT id FROM compliance_domains WHERE name = 'Formation & Registration'), 2, '{"business_type": ["limited_company"]}'),
((SELECT id FROM concierge_stages WHERE stage_number = 1), 'Check Companies House registration', 'Verify your company is correctly registered at Companies House and your details are up to date.', 'external_link', 'https://find-and-update.company-information.service.gov.uk/', (SELECT id FROM compliance_domains WHERE name = 'Formation & Registration'), 3, '{"business_type": ["limited_company", "partnership"]}'),
((SELECT id FROM concierge_stages WHERE stage_number = 1), 'Register with the ICO', 'If you process personal data (customer names, emails, etc.), you likely need to register with the Information Commissioner''s Office. Costs £40/year.', 'external_link', 'https://ico.org.uk/registration/new', (SELECT id FROM compliance_domains WHERE name = 'Data Protection'), 4, '{}'),
((SELECT id FROM concierge_stages WHERE stage_number = 1), 'Set up your Unique Taxpayer Reference', 'You need a UTR number to file your Self Assessment tax return. HMRC sends this by post after registration.', 'mark_done', NULL, (SELECT id FROM compliance_domains WHERE name = 'Tax & Financial'), 5, '{"business_type": ["sole_trader"]}'),
((SELECT id FROM concierge_stages WHERE stage_number = 1), 'Register for VAT (if applicable)', 'You must register for VAT if your turnover exceeds £90,000 in any 12-month period. You can also register voluntarily.', 'external_link', 'https://www.gov.uk/vat-registration', (SELECT id FROM compliance_domains WHERE name = 'Tax & Financial'), 6, '{}');

-- Stage 2: Operate Safely (7 tasks)
INSERT INTO concierge_tasks (stage_id, title, description, action_type, action_url, domain_id, display_order, applies_to) VALUES
((SELECT id FROM concierge_stages WHERE stage_number = 2), 'Get Employer''s Liability insurance', 'If you have employees, you must have Employer''s Liability insurance with at least £5 million cover. It''s the law.', 'mark_done', NULL, (SELECT id FROM compliance_domains WHERE name = 'Insurance'), 1, '{"min_headcount": 2}'),
((SELECT id FROM concierge_stages WHERE stage_number = 2), 'Consider Public Liability insurance', 'Not legally required for most businesses, but strongly recommended if customers visit your premises or you work at client sites.', 'mark_done', NULL, (SELECT id FROM compliance_domains WHERE name = 'Insurance'), 2, '{}'),
((SELECT id FROM concierge_stages WHERE stage_number = 2), 'Create a privacy policy', 'If you collect any personal data (even just customer email addresses), you need a privacy policy. It must explain what data you collect and why.', 'mark_done', NULL, (SELECT id FROM compliance_domains WHERE name = 'Data Protection'), 3, '{}'),
((SELECT id FROM concierge_stages WHERE stage_number = 2), 'Issue employment contracts', 'All employees must receive a written statement of employment terms on or before their first day of work.', 'mark_done', NULL, (SELECT id FROM compliance_domains WHERE name = 'Employment & People'), 4, '{"min_headcount": 2}'),
((SELECT id FROM concierge_stages WHERE stage_number = 2), 'Set up workplace pension (auto-enrolment)', 'If you have employees, you must automatically enrol eligible staff into a workplace pension scheme.', 'external_link', 'https://www.thepensionsregulator.gov.uk/en/employers', (SELECT id FROM compliance_domains WHERE name = 'Employment & People'), 5, '{"min_headcount": 2}'),
((SELECT id FROM concierge_stages WHERE stage_number = 2), 'Complete a basic risk assessment', 'Every employer must carry out a risk assessment. If you have 5 or more employees, it must be written down.', 'mark_done', NULL, (SELECT id FROM compliance_domains WHERE name = 'Health & Safety'), 6, '{"min_headcount": 2}'),
((SELECT id FROM concierge_stages WHERE stage_number = 2), 'Display your Health & Safety law poster', 'All employers must display the approved Health & Safety law poster where employees can easily read it.', 'mark_done', NULL, (SELECT id FROM compliance_domains WHERE name = 'Health & Safety'), 7, '{"min_headcount": 2}');

-- Stage 3: Build Good Habits (5 tasks)
INSERT INTO concierge_tasks (stage_id, title, description, action_type, action_url, domain_id, display_order, applies_to) VALUES
((SELECT id FROM concierge_stages WHERE stage_number = 3), 'Set up a filing system for tax records', 'Keep records of all business income and expenses. You must keep these for at least 5 years after the 31 January deadline.', 'mark_done', NULL, (SELECT id FROM compliance_domains WHERE name = 'Tax & Financial'), 1, '{}'),
((SELECT id FROM concierge_stages WHERE stage_number = 3), 'Add key deadlines to your calendar', 'Check your Compliance Calendar — we have already added your statutory deadlines. Make sure you know when they are.', 'internal_workflow', '/app/calendar', NULL, 2, '{}'),
((SELECT id FROM concierge_stages WHERE stage_number = 3), 'Upload your key documents', 'Store copies of your important documents (insurance certificates, contracts, registrations) in your Document Vault.', 'internal_workflow', '/app/documents', NULL, 3, '{}'),
((SELECT id FROM concierge_stages WHERE stage_number = 3), 'Review your compliance health score', 'Check your Dashboard regularly. Aim to keep all domains green by completing tasks before their deadlines.', 'internal_workflow', '/app/dashboard', NULL, 4, '{}'),
((SELECT id FROM concierge_stages WHERE stage_number = 3), 'Set up a monthly review habit', 'Spend 15 minutes at the start of each month reviewing your compliance status. We will send you a reminder.', 'mark_done', NULL, NULL, 5, '{}');
